-- 코드를 입력하세요
SELECT out1.ANIMAL_ID, out1.NAME
FROM ANIMAL_OUTS out1
WHERE out1.ANIMAL_ID NOT IN (
    SELECT out2.ANIMAL_ID
    FROM ANIMAL_OUTS out2
    INNER JOIN ANIMAL_INS in1 on out2.ANIMAL_ID = in1.ANIMAL_ID
)