-- 코드를 입력하세요
WITH SUB AS (
    SELECT orders.PRODUCT_ID, SUM(orders.AMOUNT) as TOTAL_AMOUNT
    FROM FOOD_ORDER orders
    WHERE orders.PRODUCE_DATE >= '2022-05-01' AND orders.PRODUCE_DATE < '2022-06-01'
    GROUP BY orders.PRODUCT_ID
)
SELECT product.PRODUCT_ID, product.PRODUCT_NAME, sub.TOTAL_AMOUNT * product.PRICE as TOTAL_SALES
FROM SUB sub
INNER JOIN FOOD_PRODUCT product on product.PRODUCT_ID = sub.PRODUCT_ID
ORDER BY TOTAL_SALES desc, PRODUCT_ID asc;